# Generated by Django 4.2.7 on 2023-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="question_text",
        ),
    ]
