# Generated by Django 4.2.7 on 2023-11-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_message_author_message_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="telegram_message_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="diary.user",
            ),
        ),
    ]
