# Generated by Django 4.2.7 on 2023-11-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0005_alter_user_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="goal",
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
