# Generated by Django 4.2.7 on 2023-11-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0006_alter_user_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(max_length=20000),
        ),
    ]
