# Generated by Django 4.2.7 on 2023-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0007_alter_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
