# Generated by Django 4.2.7 on 2023-11-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0009_alter_message_telegram_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_week_in_review",
            field=models.BooleanField(default=False),
        ),
    ]
