# Generated by Django 4.2.7 on 2023-11-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0010_user_enable_week_in_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_reminders",
            field=models.BooleanField(default=False),
        ),
    ]
